### ISSUE TITLE
Are the kernel packages mixed (CB and CLTS)?

### ISSUE THREAD

**Issue by msmafra** [CachyOS/linux-cachyos#207]
Hello there!

I'm not sure what is happening here: 6.6.10-cb1.0 and 6.6.10-clts1.0 at the same time or are the same now? I wasn't using the LTS.

```
 ❯ dnf5 upgrade
Updating and loading repositories:
Repositories loaded.
Package                                                 Arch   Version                                                 Repository                                                       Size
Installing:
 kernel-cachyos-core                                    x86_64 6.6.10-cb1.0.fc39                                       copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos   87.0 MiB
 kernel-cachyos-modules                                 x86_64 6.6.10-cb1.0.fc39                                       copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos   96.7 MiB
Installing dependencies:
 kernel-cachyos-lts-core                                x86_64 6.6.10-clts1.0.fc39                                     copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos   87.0 MiB
 kernel-cachyos-lts-devel                               x86_64 6.6.10-clts1.0.fc39                                     copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos   66.0 MiB
 kernel-cachyos-lts-devel-matched                       x86_64 6.6.10-clts1.0.fc39                                     copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos    0.0   B
 kernel-cachyos-lts-modules                             x86_64 6.6.10-clts1.0.fc39                                     copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos   96.6 MiB

Transaction Summary:
 Installing:        6 packages

Total size of inbound packages is 235 MiB. Need to download 235 MiB.
After this operation 433 MiB will be used (install 433 MiB, remove 0 B).
Is this ok [Y/n]:

dnf5 search kernel-cachyos
Updating and loading repositories:
Repositories loaded.
Matched fields: name (exact)
 kernel-cachyos.src: The Linux Kernel with Cachyos-BORE-EEVDF Patches
 kernel-cachyos.x86_64: The Linux Kernel with Cachyos-BORE-EEVDF Patches
Matched fields: name
 kernel-cachyos-bore.src: The Linux Kernel with Cachyos-BORE Patches
 kernel-cachyos-bore.x86_64: The Linux Kernel with Cachyos-BORE Patches
 kernel-cachyos-bore-core.x86_64: Kernel core package
 kernel-cachyos-bore-devel.x86_64: Development package for building kernel modules to match the cachyos-bore kernel
 kernel-cachyos-bore-devel-matched.x86_64: Meta package to install matching core and devel packages for a given cachyos-bore kernel
 kernel-cachyos-bore-eevdf.src: The Linux Kernel with Cachyos-BORE-EEVDF Patches
 kernel-cachyos-bore-eevdf.x86_64: The Linux Kernel with Cachyos-BORE-EEVDF Patches
 kernel-cachyos-bore-eevdf-core.x86_64: Kernel core package
 kernel-cachyos-bore-eevdf-devel.x86_64: Development package for building kernel modules to match the cachyos-bore-eevdf kernel
 kernel-cachyos-bore-eevdf-devel-matched.x86_64: Meta package to install matching core and devel packages for a given cachyos-bore-eevdf kernel
 kernel-cachyos-bore-eevdf-headers.x86_64: Header files for the Linux kernel for use by glibc
 kernel-cachyos-bore-eevdf-modules.x86_64: Kernel modules to match the core kernel
 kernel-cachyos-bore-eevdf-rt.src: The Linux Kernel with Cachyos-BORE-EEVDF Patches
 kernel-cachyos-bore-eevdf-rt.x86_64: The Linux Kernel with Cachyos-BORE-EEVDF Patches
 kernel-cachyos-bore-eevdf-rt-core.x86_64: Kernel core package
 kernel-cachyos-bore-eevdf-rt-devel.x86_64: Development package for building kernel modules to match the cachyos-bore-eevdf-rt kernel
 kernel-cachyos-bore-eevdf-rt-devel-matched.x86_64: Meta package to install matching core and devel packages for a given cachyos-bore-eevdf-rt kernel
 kernel-cachyos-bore-eevdf-rt-headers.x86_64: Header files for the Linux kernel for use by glibc
 kernel-cachyos-bore-eevdf-rt-modules.x86_64: Kernel modules to match the core kernel
 kernel-cachyos-bore-headers.x86_64: Header files for the Linux kernel for use by glibc
 kernel-cachyos-bore-lto.src: The Linux Kernel with Cachyos-EEVDF-BORE Patches
 kernel-cachyos-bore-lto.x86_64: The Linux Kernel with Cachyos-EEVDF-BORE Patches
 kernel-cachyos-bore-lto-core.x86_64: Kernel core package
 kernel-cachyos-bore-lto-devel.x86_64: Development package for building kernel modules to match the cachyos-bore-lto kernel
 kernel-cachyos-bore-lto-devel-matched.x86_64: Meta package to install matching core and devel packages for a given cachyos-bore-lto kernel
 kernel-cachyos-bore-lto-headers.x86_64: Header files for the Linux kernel for use by glibc
 kernel-cachyos-bore-lto-modules.x86_64: Kernel modules to match the core kernel
 kernel-cachyos-bore-modules.x86_64: Kernel modules to match the core kernel
 kernel-cachyos-core.x86_64: Kernel core package
 kernel-cachyos-devel.x86_64: Development package for building kernel modules to match the cachyos kernel
 kernel-cachyos-devel-matched.x86_64: Meta package to install matching core and devel packages for a given cachyos kernel
 kernel-cachyos-headers.x86_64: Header files for the Linux kernel for use by glibc
 kernel-cachyos-lts.src: The Linux Kernel with Cachyos-LTS Patches
 kernel-cachyos-lts.x86_64: The Linux Kernel with Cachyos-LTS Patches
 kernel-cachyos-lts-core.x86_64: Kernel core package
 kernel-cachyos-lts-devel.x86_64: Development package for building kernel modules to match the cachyos-lts kernel
 kernel-cachyos-lts-devel-matched.x86_64: Meta package to install matching core and devel packages for a given cachyos-lts kernel
 kernel-cachyos-lts-headers.x86_64: Header files for the Linux kernel for use by glibc
 kernel-cachyos-lts-modules.x86_64: Kernel modules to match the core kernel
 kernel-cachyos-modules.x86_64: Kernel modules to match the core kernel
 kernel-cachyos-rt.src: The Linux Kernel with Cachyos-BORE-EEVDF Patches
 kernel-cachyos-rt.x86_64: The Linux Kernel with Cachyos-BORE-EEVDF Patches
 kernel-cachyos-rt-core.x86_64: Kernel core package
 kernel-cachyos-rt-devel.x86_64: Development package for building kernel modules to match the cachyos-rt kernel
 kernel-cachyos-rt-devel-matched.x86_64: Meta package to install matching core and devel packages for a given cachyos-rt kernel
 kernel-cachyos-rt-headers.x86_64: Header files for the Linux kernel for use by glibc
 kernel-cachyos-rt-modules.x86_64: Kernel modules to match the core kernel
```
