### ISSUE TITLE
compiling linux-cachyos in OBS

### ISSUE THREAD

**Issue by lavilao** [CachyOS/linux-cachyos#78]
Has anyone successfully compiled linux-cachyos in opensuse OBS (https://build.opensuse.org)? I am not talking about building it for opensuse but to use OBS to build it for arch. I have tried but it always gives me error can not parse name from PKGBUILD (the package compiles fine in my machine). So, does anyone has experience with this? Thanks in advice!
PD: are the non x86_64_v3/4 lto packages going to return? celerons don't supported avx until recently so even though are not that old they are not v3.

**Comment by ptr1337** [comment]
I can't help you about OBS sadly.

Actually the LTO packages for x86-64 generic (v1) wont come back. Actually in general we really have not many v1 users, and compiling 7 different additional kernels to the repo needs a lot of processing power.
The LTO kernels are only available for x86-64-v3.

 You can find the default, gcc build kernels in the repo for x86-64(-v1). The still compile them into the repo. Only LTO Kernels not anymore.

**Comment by lavilao** [comment]
@ptr1337 shame, I get it though. Thanks for your time.
@sirlucjan thats the thing, I have compiled linux-clear-llvm but for some reason linux-cachyos won't. it always goves error that could not parse the pkgbuild name

**Comment by ptr1337** [comment]
> @ptr1337 shame, I get it though. Thanks for your time. @sirlucjan thats the thing, I have compiled linux-clear-llvm but for some reason linux-cachyos won't. it always goves error that could not parse the pkgbuild name

I think this is due that it does not read the env vars correctly out.
Please change the pkgname to something like linux-cachyos, then it should work proper.

https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos/PKGBUILD#L197

Actually we need the $pkgsuffix to provide proper support for zfs.

**Comment by lavilao** [comment]
changed, it still broken T_T
here it is if someone wants to look at it https://build.opensuse.org/package/show/home:Tian/linux-cachyos-silvermont

**Comment by ptr1337** [comment]
> changed, it still broken T_T here it is if someone wants to look at it https://build.opensuse.org/package/show/home:Tian/linux-cachyos-silvermont

I checked the PKGBUILD.
Please try following one:
https://paste.cachyos.org/p/8922c51.fish

Main part changed:

```
pkgsuffix=cachyos-bore-lto
pkgbase=linux-cachyos-bore-lto
```

**Comment by lavilao** [comment]
broken: can not parse name from PKGBUILD 
T_T

**Comment by lavilao** [comment]
is there a way to get logs from obs? at least what line is the one with troubles would be fine

**Comment by ptr1337** [comment]
I really dont understand why this is happening.
Im not used to its buildsystem. Maybe the buildsystem needs to be done way more basic.

**Comment by lavilao** [comment]
agreed, btw what buildsystem do you use? is it free or paid?

**Comment by ptr1337** [comment]
We have a own buildserver with a 13900K as CPU. This is used to rebuild the arch repo in x86-64-v3 and the Kernels.
So, its paid and not really cheap. :)

You could also use a github action to build the Kernel, that should work

**Comment by lavilao** [comment]
> You could also use a github action to build the Kernel, that should work
>
how? I have seen a lot of projects do this but never figured how to do it

**Comment by lavilao** [comment]
> We have a own buildserver with a 13900K as CPU.
>
😳

**Comment by lavilao** [comment]
> Most likely OBS is targeting on pkgname, which we have defined at the end. I'm not sure if this helps, but you can try. You can also just use GitHub Actions to put up built packages as artifacts.

mmm, can try what? english its not my main so I dont get it, sorry 🙇🏾‍♂️

**Comment by lavilao** [comment]
Will this work?
```
name: Build and lint
on:
  push:
    paths:
      - 'linux-cachyos/PKGBUILD'
      - '.github/workflows/lint.yml'
  workflow_dispatch:
jobs:
  linux-cachyos-bore-lto:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build (LLVM)
      id: makepkg
      uses: CachyOS/pkgbuild-action@master
      with:
        pkgdir: "linux-cachyos-bore"
        namcapExcludeRules: "invalidstartdir"
        makepkgArgs: "--skipchecksums --skippgpcheck --noconfirm -s"
```
I have already edited the pkgbuild so it uses lto full, silvermont subarch, etc.

**Comment by lavilao** [comment]
Error: Mismatched .SRCINFO. Update with: makepkg --printsrcinfo > .SRCINFO

**Comment by lavilao** [comment]
power just went away, so if I dont answer its not that I dont have interest is that I dont have power T_T

**Comment by lavilao** [comment]
> Yes, but it doesn't upload artifacts, you can read about them here:
> 
> https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#about-workflow-artifacts

what about now? I have a doubt though, the makepkg should build 2 files, how do I save both? should I set two names with two paths or another upload job?
```
name: Build and lint
on:
  push:
    paths:
      - 'linux-cachyos-bore/PKGBUILD'
      - '.github/workflows/lint.yml'
  workflow_dispatch:
jobs:
  linux-cachyos-bore-lto:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build (LLVM)
      id: makepkg
      uses: CachyOS/pkgbuild-action@master
      with:
        pkgdir: "linux-cachyos-bore"
        namcapExcludeRules: "invalidstartdir"
        makepkgArgs: "--skipchecksums --skippgpcheck --noconfirm -s"
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: linux-cachyos-silvermont
        path: linux-cachyos-silvermont.tar.zst
```
